### ISSUE TITLE
Add link to action handler blog post in README

### ISSUE THREAD

**Issue by kjellmorten** [ZachPerkitny/redux-handler-middleware#1]
Hi, @ZachPerkitny!

Thanks for `redux-handler-middleware`! I planned on writing something similar myself, but luckily I discovered your contribution instead.

I've just used it as an example in this blog post: https://medium.com/@kjellmorten/a-simpler-way-to-handle-async-in-redux-bc2a4b952f67

The article could also serve as another example in the README, of how this middleware is useful. I'll be happy to create a PR if you agree. :)

**Comment by ZachPerkitny** [comment]
Great article, and yeah definitely feel free to.
